//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int Id_Documento { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> Fecha_de_Lanzamiento { get; set; }
        public int Autor { get; set; }
        public int Categoría { get; set; }
        public int Idioma { get; set; }
        public string No_Paginas { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Idioma Idioma1 { get; set; }
    }
}
